version: '3.4'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fitnesslybackup
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - fitnessly-mvc-development_fitnessly_network



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: fitnessly-mvc-development-db-1
    ports:
      - "8080:80"
    networks:
      - fitnessly-mvc-development_fitnessly_network


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="Server=fitnessly-mvc-development-db-1;Database=fitnesslybackup;User=root;"
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_URLS=https://+:443
    ports:
      - "7187:443"
    networks:
      - fitnessly-mvc-development_fitnessly_network


  frontend:
    build:
      context: ./reactprojectfitnessly
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - fitnessly-mvc-development_fitnessly_network


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certificates
    depends_on:
      - backend
      - frontend
    networks:
      - fitnessly-mvc-development_fitnessly_network


networks:
   fitnessly-mvc-development_fitnessly_network: 
     external: true

volumes:
  db_data: