version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fitnesslybackup
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=fitnesslybackup;User=root;
    ports:
      - "5001:80"

  frontend:
    build:
      context: ./reactprojectfitnessly
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - backend

volumes:
  db_data:
