name: CI

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore .NET Core dependencies
        run: dotnet restore

      - name: Build .NET Core project
        run: dotnet build --no-restore

      - name: Test .NET Core project
        run: dotnet test --no-build --verbosity normal

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./reactprojectfitnessly

      - name: Build React app
        run: npm run build
        working-directory: ./reactprojectfitnessly

      - name: Test React app
        run: npm test
        working-directory: ./reactprojectfitnessly
